### ISSUE TITLE
Maintainership transfer

### ISSUE THREAD

**Issue by Amanieu** [alexcrichton/net2-rs#102]
This crate is no longer maintained, but @jclulow and @pfmooney have offered to take over maintenance as part of the @deprecrated organization.

Pinging @rust-lang/libs for approval:

* [x]  @Amanieu
* [x]  @SimonSapin
* [x]  @dtolnay
* [x]  @sfackler
* [ ]  @withoutboats
* [ ]  @LukasKalbertodt
* [x]  @BurntSushi

**Comment by BurntSushi** [comment]
I don't have access to tick my checkbox, but SGTM!

**Comment by bluejekyll** [comment]
I just want to make sure people know that folks moved over to using the maintained and better design (IMO) of https://github.com/alexcrichton/socket2-rs

**Comment by Amanieu** [comment]
Yes but apparently this crate is still widely used in the ecosystem, which means that there is value is continuing to maintain it, e.g. to add support for new platforms (#101).

**Comment by jclulow** [comment]
We are happy to put whatever signage up about deprecation and what you should do instead that folks think is wise!

**Comment by bluejekyll** [comment]
To me for such a low level library, I would hope that we could convince folks to migrate, or maybe there’s a way to create an API shim that calls through to socket2.

Otherwise we’ll end up with both in a lot of networking code.

**Comment by SimonSapin** [comment]
SGTM, thanks to the new maintainers for volunteering!

**Comment by dtolnay** [comment]
@rfcbot reviewed

**Comment by emilyalbini** [comment]
I'll wait a couple of days to see if @withoutboats or @LukasKalbertodt have any opinion on this, then I'll transfer the repo.

**Comment by pfmooney** [comment]
Is it acceptable to move forward on this with the two abstentions?

**Comment by emilyalbini** [comment]
@pfmooney @jclulow could you add me to the @deprecrated organization with permissions to create repositories? I'll then transfer the repository and leave that org :)

**Comment by emilyalbini** [comment]
Transferred the repository!

**Comment by pfmooney** [comment]
> Transferred the repository!

Thanks!  I've created the `crates` team under the `deprecrated` organization.  I assume push rights on crates.io can be assigned to a team like that?

**Comment by pfmooney** [comment]
If someone can add @jclulow or I to the crate on crates.io, we can do the rest.  Thanks

**Comment by sfackler** [comment]
I believe @alexcrichton is the only person who has the ability to do that - people who are only owners via team membership can't add owners.

**Comment by alexcrichton** [comment]
Ok I've invited @pfmooney to the crate on crates.io

**Comment by pfmooney** [comment]
> Ok I've invited @pfmooney to the crate on crates.io

Accepted.  Thanks!
