### ISSUE TITLE
github.com/deprecated-rs maybe?

### ISSUE THREAD

**Issue by pravic** [alexcrichton/net2-rs#104]
Why github.com/deprecated? Should this namespace cover other languages than Rust?

If Rust only, then it's better to name it github.com/deprecated-rs.

**Comment by JeanMertz** [comment]
It's subtle, but the org name is deprec**r**ated, i.e. it's a list of _deprecated crates_. Seems appropriate to me 😃

**Comment by pfmooney** [comment]
> It's subtle, but the org name is deprec**r**ated, i.e. it's a list of _deprecated crates_.

Exactly
