### ISSUE TITLE
net2 assumes the layout of std::net::SocketAddrV{4,6} matches libc::sockaddr

### ISSUE THREAD

**Issue by Thomasdezeeuw** [alexcrichton/net2-rs#105]
The problem code is here: https://github.com/deprecrated/net2-rs/blob/77a6eb4d5eb36adc81ee21ab7ffebc62fdf2ab88/src/socket.rs#L87-L142

It assumes that the layout of `std::net::SocketAddrV{4,6}` matches `libc::sockaddr`, but this can't be assumed.

Related issues: https://github.com/tokio-rs/mio/issues/1386, https://github.com/rust-lang/socket2-rs/issues/119, https://github.com/rust-lang/rust/pull/78802.

Mio has roughly the same code, this was fixed in https://github.com/tokio-rs/mio/pull/1388, for socket2: https://github.com/rust-lang/socket2-rs/pull/120.

**Comment by faern** [comment]
I'm working on porting my code from the `socket2` and `mio` PRs to this crate.
