### ISSUE TITLE
Yank all `0.2` versions older than `0.2.36`

### ISSUE THREAD

**Issue by faern** [alexcrichton/net2-rs#107]
Due to #106. If the standard library ever do change the memory layout of `SocketAddr`, usage of this crate of versions before `0.2.36` will have undefined behaviour and invalid memory access and lead to segfaults. And even if the standard library never do change the layout of those types, those versions of this crate still makes assumptions they should not.

This is exactly what yanking is for. Marking a release as "should not be used". I think all versions of `net2` from `0.2.0` through `0.2.35` should be yanked from crates.io.

Related issues on other crates having the same problem: https://github.com/rust-lang/socket2-rs/issues/139, https://github.com/tokio-rs/mio/issues/1412

**Comment by jclulow** [comment]
Should we also yank all 0.1 versions?  It seems like that `addr2raw()` implementation has been there since the beginning:

https://github.com/deprecrated/net2-rs/commit/42bc9219624561505fa54d9866bc5024995043fe#diff-917ff224180b881299cdcef7bc14e710509229092ea4e6599861680bc0a2a458R65-R74

**Comment by faern** [comment]
It has the same bug yes. We have not released any patch release fixing it for the `0.1` branch. But looking at the download stats, it has virtually zero downloads. Yes yank them IMO, **they are unsound**

**Comment by faern** [comment]
Ping @jclulow ?

**Comment by pfmooney** [comment]
I believe all of the older versions have been yanked.

**Comment by faern** [comment]
Amazing! Thank you.
