### ISSUE TITLE
Documentation request for UdpSocketExt

### ISSUE THREAD

**Issue by xrl** [alexcrichton/net2-rs#17]
Can you provide an example for sending UDP multicast with `UdpSocketExt`? I don't know how to list out the `Ipv4Addr`'s on the current host and I think that would useful to new `net2` users.

**Comment by alexcrichton** [comment]
I'm all for adding documentation! I'm not quite sure what you're trying to do though, what do you mean by listing out addresses on the current host? 

Also note that most methods in this crate simply directly correspond to various options you'd find in C here and there, so any examples in the wild should be directly translatable to Rust as well.

**Comment by xrl** [comment]
I'm trying to send the same message over multicast through all connected interfaces (osx: `en0` and `lo`. or on linux: `eth{0,1,2}`). But I do realize I'm a newb in these APIs. I'm not sure what the C stdlib equivalent would be.

**Comment by xrl** [comment]
OK, so I'm looking for `getifaddrs` in Rust. Led me to a maidsafe project: https://github.com/maidsafe/crust/blob/master/src/getifaddrs.rs . I'll keep going and perhaps contribute back some docs :)

**Comment by alexcrichton** [comment]
Ah ok, in that case the `getifaddrs` function currently isn't bound here so I'm gonna close this, but feel free to add docs if some are needed!
