### ISSUE TITLE
Add `local_addr` method to TcpBuilder

### ISSUE THREAD

**Issue by canndrew** [alexcrichton/net2-rs#26]
I've got a `TcpBuilder` which is bound and I'd like to get it's local address. I don't see why this type shouldn't support the `local_addr` method the same as `TcpListener` and `TcpStream` do.

**Comment by alexcrichton** [comment]
Sounds reasonable to me!

**Comment by ustulation** [comment]
_Bump_ any news when this will be done ?

**Comment by alexcrichton** [comment]
Ah it's fine to do any time, just haven't had time to get around to doing this yet though. PRs are of course always welcome!

**Comment by nbaksalyar** [comment]
@alexcrichton, could you please publish the latest version on crates.io and close this issue?
Thanks!

**Comment by alexcrichton** [comment]
Done!
