### ISSUE TITLE
TCP keepalive functionality isn't ideal

### ISSUE THREAD

**Issue by sfackler** [alexcrichton/net2-rs#29]
I discovered during the implementation of RFC 1461 that we should tweak the APIs that we expose related to TCP keepalive. Right now we have a getter and setter for an `Option<Duration>`, but there are two problems with this:
- There are two distinct operations at the socket level that are being conflated - enabling keepalive and customizing the associated interval. We'd probably want to separate these out.
- You can't retrieve the keepalive interval on Windows.

**Comment by sfackler** [comment]
A conservative move would be to just change the existing methods to work with a bool and punt on the interval for now. Java doesn't allow the interval to be adjusted, for example.

**Comment by alexcrichton** [comment]
I'd be fine with just a bool for now, although we've already got the implementation for handling the `Duration` so we could at least have the setter?

**Comment by sfackler** [comment]
We could, yeah. The other bit of platform-dependence there is that the Windows versions's call both enables/disables keepalive and sets the interval, where the Unix one just sets the interval.

**Comment by alexcrichton** [comment]
This is kinda out of cache for me unfortunately, but in that case maybe there could just be a unix-specific extension? To enable the keepalive without setting an interval

**Comment by sfackler** [comment]
You can also do that on Windows, actually.

**Comment by the8472** [comment]
Setting the initial offset and interval is pretty much necessary for keepalive to be have an effect on stateful firewalls at all because the defaults are essentially useless for that purpose, it is *two hours*.

**Comment by pfmooney** [comment]
net2 is deprecated and under sustaining maintenance now, accepting only bugfixes and patches to enable new rust platforms.
