### ISSUE TITLE
No need to incite segregation between IPv4 and IPv6

### ISSUE THREAD

**Issue by nodakai** [alexcrichton/net2-rs#32]
C programmers have been advised to use `getaddrinfo(3)` for nearly two decades by which their program can be protocol-agnostic. Rust API shouldn't try to go back in time to the days when it was not available.

Of course you can give hints to `getaddrinfo(3)` in order to opt-out from IPv6 connections if you're not a great fan of IPv6 (like I'm not.)

In fact the same goes for TCP vs UDP in principle.

**Comment by alexcrichton** [comment]
I don't understand this issue, this library doesn't even call `getaddrinfo`. Could you clarify what you'd like to see changed?

**Comment by nodakai** [comment]
> Could you clarify what you'd like to see changed?

Let's begin with unifying `TcpBuilder::new_v4()` and `TcpBuilder::new_v6()` into `TcpBuilder::new()`.

> this library doesn't even call `getaddrinfo`.

Yeah but I got an impression that you guys would be adding host/service name lookup to this crate from @aturon's [comment](https://github.com/rust-lang/rust/issues/27705#issuecomment-202511878). Given that `getaddrinfo(3)` has been the best practice for host/service name lookup partly because of its unified handling of IPv4 and IPv6, I'm naturally expecting this crate to incorporate it in the near future.

By extension we are led to the idea of unification of `TcpBuilder` and `UdpBuilder` (or an hypothetical `RawIpBuilder` etc) but that may not be practical or even feasible when `std::net` already distinguishes between `TcpStream` and `UdpSocket`.

**Comment by alexcrichton** [comment]
The purpose of this library is to be as direct a binding as the underlying syscalls as possible. As great as it would be to not have to specify v4 or v6 at creation time, that's just now how the syscalls work. If we move other functionality into this library we should certainly try to abstract over v4/v6, but at this time I don't think this is actionable so closing.
