### ISSUE TITLE
Get/Set socket buffers sizes

### ISSUE THREAD

**Issue by arthurprs** [alexcrichton/net2-rs#37]
I think it'd be interesting to have functions for setting/getting socket buffer sizes in net2.

**Comment by alexcrichton** [comment]
Certainly! Wanna send a PR for this? Should be relatively straightforward to mirror the existing bindings.

**Comment by arthurprs** [comment]
Ya, I'll try to find some time in the next few days.

**Comment by alexcrichton** [comment]
Done now! (#39)
