### ISSUE TITLE
POSIX interface

### ISSUE THREAD

**Issue by nathansizemore** [alexcrichton/net2-rs#38]
Hey-o!

Not sure if this is the place to for this, but figured anyone in the community caring about the evolution of `std::net` is probably using this crate and will be here.

It took me a bit too long to figure out this crate was around, and that [RFC 1158](https://github.com/alexcrichton/rfcs/blob/net2.1/text/0000-io-net-2.1.md) was a thing. It appears this crate has been baking for a bit with the standard _Rusty_ style API with the addition of the _Builder-like_ API. Is it too late to recommend that `std::net` should provide a safe Socket wrapper that exposes a POSIX style API (POSIX sockets won the network API war, even Microsoft conforms) in order to make interfacing with current lower level system network code a little less cumbersome to work with? 

For any serious networking application with OS level options, you already have to pull out the inner and do unsafe operations from the libc crate, or with your own shims. Also, because of the current `std::net::TcpStream` and friends wrapping a `FileDesc` and using `F_DUPFD` when cloning, it can make for some unexpected weirdness when interacting with other system level interfaces expecting fds.

I only ask because I'm already on the path of making this a thing, but really just for Unix. But if there is interest, or it would be worth it, I wouldn't mind putting those efforts into this crate with a PR or RFC or whatever and also including the Win calls. The API surface I have in mind would be everything [here](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_socket.h.html) minus `recvmsg/sendmsg` because of the heavy use of C macros associated with setting those data structures up properly. Most of the flags and functions are available through current `libc`/`winapi` crates, with the remaining only a few PRs away to keep from hard-coding flags. If this is also too big of a change (Obv it will be breaking), I can do a RFC along with the PR as well?

**Comment by alexcrichton** [comment]
Thanks for the report! Yeah it's too late to radically design the `std::net` module, but it's intended that this repository would serve for any other flavors of extensions or use cases. It's currently our belief that we can have a "rustic" interface while also preserving maximal flexibility in terms of what underlying syscalls need to be issued.

Do you have some concrete use cases which aren't enabled by net2 + std::net today? Would be good to know if the design needs to change!

**Comment by nathansizemore** [comment]
As far as just flat out things not possible currently, only a few various options through `getsockopt` and `setsockopt` are left. Of the options, now that the buf sizes PR just got accepted, I'm only missing one that I care about, and I'll be sending a PR to cover this right after I get this comment finished :)

As far as general use cases that I'm currently having trouble working directly with `std::net` go, I thought I had one, but by the time I was finished writing it all out here, I discovered that it was just me being dumb, and found a better way to handle it. Funny how just by writing out your problem sometimes causes the solution to dawn on you!

**Comment by nathansizemore** [comment]
Never mind about the PR, it appears that option is there as well and I just missed it.

**Comment by alexcrichton** [comment]
Good to hear it worked out! We're definitely still missing a number of common socket options I think, so if you run across any that need to be added feel free to send a PR!
