### ISSUE TITLE
Set `SO_REUSEADDR` same as stdlib's net

### ISSUE THREAD

**Issue by badboy** [alexcrichton/net2-rs#4]
Currently Rust's stdlib net module sets `SO_REUSEADDR` for a `TcpListener` on `bind`:
https://github.com/rust-lang/rust/blob/ddc28298b9133e6a9cc39e276f9feff51d808949/src/libstd/sys/common/net.rs#L325-L328

net2 does not.
I'm not sure whether this should come as a configuration option in the builder, as proposed in the RFC, or as the default for sockets (atleast for not-Windows systems) like Rust does.

(Edit: Also, I guess `SO_REUSEADDR` is not used on Windows because it has a slightly different meaning there)

**Comment by seppo0010** [comment]
Thanks for filing this, @badboy.

I'm not sure having `SO_REUSEADDR` by default is needed, but at least an opt-in method would be nice.

**Comment by alexcrichton** [comment]
Yeah the purpose of `net2` is to be as thin a layer as possible over the system, so this probably won't set this by default, but certainly a unix-specific extension trait could be used to set this option!

**Comment by seppo0010** [comment]
The unix-specific trait will be added to net2? Are you gonna work on that or should I start a new crate? One of the problems of breaking it down into a separate one is that some of the properties are not `pub`.

**Comment by alexcrichton** [comment]
Ah yeah I'd be more than willing to add it here, and I'll try to do so today at some point!

**Comment by seppo0010** [comment]
:+1: :grinning: Thanks.

**Comment by seppo0010** [comment]
Actually, it needn't to be unix-specific, since windows also have SO_REUSEADDR, although it has a different meaning. I'll leave it up to you to figure out what to do.

**Comment by alexcrichton** [comment]
Perfect!

**Comment by alexcrichton** [comment]
as in, sounds like it could just be added as a method to the extension traits and implementations
