### ISSUE TITLE
Latest 0.2 release broke compatibility with Rust 1.6

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/net2-rs#40]
https://github.com/rust-lang-nursery/net2-rs/blob/master/Cargo.toml#L14 doesn't work on Rust 1.6 (which mio currently supports).

https://travis-ci.org/carllerche/mio/jobs/138896303

**Comment by alexcrichton** [comment]
Yeah unfortunately right now we haven't quite decided on what the minimum version of Rust is to support (see https://github.com/rust-lang/rfcs/pull/1619), so regressions like this can happen from time to time. PRs to move the version back though are of course always welcome!

**Comment by MarkSwanson** [comment]
Fyi my project doesn't build because I'm using mio - which now pulls in a version of net2 that will not compile.

I can't keep up with the pace of Rust change atm.
Is there a way for me to force the net2 version that gets pulled in from mio?
(my project's Cargo.toml doesn't refer to net2)

Thanks!

**Comment by alexcrichton** [comment]
@MarkSwanson I'll just update the syntax so it's compatible, no need to juggle versions.
