### ISSUE TITLE
Refactor ext.rs

### ISSUE THREAD

**Issue by sateffen** [alexcrichton/net2-rs#43]
Hey a second time,

on my way checking how to implement #42 I saw that I just have to add some code to the ext.rs, but this file is... Hilarious. It's so long, that it's very difficult to check what I've done already, even going from  top to bottom.

Is there a special reason, why this file is so super long? Is there a chance to refactor this in separated files, so it gets simpler to maintain? I think it would help a lot.

**Comment by alexcrichton** [comment]
Much of the length just comes from documentation, but it could possible be split up into the various extension traits, and seems like a fine refactoring to me!
