### ISSUE TITLE
TcpBuilder::connect should use SocketAddr instead of ToSocketAddrs.

### ISSUE THREAD

**Issue by ghost** [alexcrichton/net2-rs#45]
If ToSocketAddrs are resolved to multiple addresses, then in case of failure
connect will be used multiple times with the same socket. This is incorrect.
After first failed connect the state of socket is unspecified and socket should
not be reused. 

Additionally, if socket is in non-blocking mode, then the connect can return
EINPROGRESS. Connection will not be aborted, and further calls to connect will
fail with EALREADY, because connection request is already in progress.

**Comment by alexcrichton** [comment]
Hm yeah with `TcpBuilder` the story here isn't great, but this is also part of the state transition from `TcpBuilder` -> `TcpStream`, so the error would also need to carry that payload unfortunately :(

**Comment by ghost** [comment]
Currently the internal socket is consumed and converted to a `TcpStream` only
if connect succeeds. So you could actually check for EINPROGRESS and still call
`to_tcp_stream` after receiving an error from connect. Not saying this is the
best way to proceed, but it is currently possible.

I was mostly concerned with different thing, i.e., exposing an API that uses
connect syscall multiple times with the same socket, all because of
`ToSocketAddrs` used as an argument to `TcpBuilder`.

**Comment by alexcrichton** [comment]
I suppose if we could go back I'd want to rethink a good portion of this crate. I feel like `TcpBuilder` never ended up pulling its own weight and I'd prefer to keep all the methods as low-level as possible (e.g. remove `ToSocketAddrs`).

**Comment by pfmooney** [comment]
net2 is deprecated and under sustaining maintenance now, accepting only bugfixes and patches to enable new rust platforms.
