### ISSUE TITLE
Introduce Raw Socket public API

### ISSUE THREAD

**Issue by DoumanAsh** [alexcrichton/net2-rs#47]
subj
Does it sound good idea to introduce such API?

Current Socket struct is pretty much for internal use, but what about letting user access it by making it public?

**Comment by DoumanAsh** [comment]
I started to work on it on my own https://github.com/DoumanAsh/lazy-socket.rs
So, but if you're going to consider introducing such API, let me know, i would gladly help :)

**Comment by alexcrichton** [comment]
Over time I've come to think that we may inevitably provide an API like this, yeah. I'd prefer to take such a step lightly as it can have ramifications beyond just the current TCP/UDP test case, but would be good to keep in mind!

**Comment by DoumanAsh** [comment]
@alexcrichton JFYI i finished, more or less, Socket struct itself. 
It is just thin wrappers over socket methods and a bit of convenience methods.
It still requires some touch up of internals, but so far seems to work more or less on Windows and Linux.
Address representation is done through `net::SocketAddr` which should be ok i suppose.

**Comment by pfmooney** [comment]
net2 is deprecated and under sustaining maintenance now, accepting only bugfixes and patches to enable new rust platforms.
