### ISSUE TITLE
How to use `set_keepalive` in nightly

### ISSUE THREAD

**Issue by seppo0010** [alexcrichton/net2-rs#5]
I'm trying to use the new net2 `set_keepalive`, but it is unclear to me how to use it.

In https://github.com/alexcrichton/net2-rs/blob/master/src/ext.rs#L165 it is implemented as a trait for `TcpStream`, but `TcpStream` already has a `set_keepalive` in nightly http://doc.rust-lang.org/nightly/std/net/struct.TcpStream.html#method.set_keepalive

Am I missing something?

**Comment by alexcrichton** [comment]
Ah you can just add a dependency like:

``` rust
net2 = { version = "0.1", features = ["nightly"] }
```

Currently this method is behind a feature because it requires the unstable `Duration` type in the standard library.

**Comment by seppo0010** [comment]
Hey @alexcrichton, I tried that and it doesn't seem to work

My change: https://github.com/seppo0010/rsedis/commit/052eb47a48aac89b434a40e0b8bed9b96da1da76

The results: https://travis-ci.org/seppo0010/rsedis/builds/73747727

**Comment by alexcrichton** [comment]
Ah you're still picking up the inherent `set_keepalive` method in the standard library, you'll probably need to use UFCS along the lines of `TcpStreamExt::set_keepalive(&foo, duration)` to get the implementation.

**Comment by seppo0010** [comment]
Ah, thanks! I was not familiar with that syntax.
