### ISSUE TITLE
Add UDP recvmmsg interface.

### ISSUE THREAD

**Issue by Albibek** [alexcrichton/net2-rs#67]
Linux, FreeBSD and maybe others have the recvmmsg call for receiving many messages from UDP socket at once. This could be a great feature for this library.

I think I could submit a PR for that, but It could be better if someone guided me a bit about where to better place this feature.

**Comment by pfmooney** [comment]
net2 is deprecated and under sustaining maintenance now, accepting only bugfixes and patches to enable new rust platforms.
