### ISSUE TITLE
Publish 0.2.4

### ISSUE THREAD

**Issue by seppo0010** [alexcrichton/net2-rs#8]
Since net2 is broken in nightly, it'd be nice to have 0.2.4 released.

On the other hand, I tried to work around by pointing my Cargo.toml to this repository, but it doesn't seem to detect the nightly feature. Should this work?

```
-[dependencies]
-net2 = { version = "0.2.2", features = ["nightly"] }
+[dependencies.net2]
+net2 = { git = "https://github.com/alexcrichton/net2-rs", features = ["nightly"] }
```

The error I'm getting:

```
src/lib.rs:71:35: 71:62 error: no associated item named `set_keepalive` found for type `net2::ext::TcpStreamExt` in the current scope
src/lib.rs:71             Stream::Tcp(ref s) => TcpStreamExt::set_keepalive(s, duration),
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

Thanks

**Comment by alexcrichton** [comment]
Done!

**Comment by seppo0010** [comment]
Just for curiosity, any idea what was I doing wrong with the `Cargo.toml` that didn't work?

**Comment by alexcrichton** [comment]
I think you also need to drop `dependencies.net2` and instead just have the key look like:

``` toml
[dependencies]
net2 = { ... }

```

**Comment by seppo0010** [comment]
Aaaah. Thanks.
