### ISSUE TITLE
Support for ICMP sockets

### ISSUE THREAD

**Issue by ghost** [alexcrichton/net2-rs#81]
I went through the RFC related to net2 and I didn't see any mention of ICMP support.
Both Linux [1] and MacOS support unprivileged sockets, with which an application could send
ICMP echo requests without being root.

I'm working on a tool that needs to send ICMP pings, and since I'll be writing some abstractions on top
of libc's stuff, I thought I might as well contribute back.

Would this be interesting for net2?

I do have the use-case, but maybe there's not enough demand for ICMP to justify adding it here.

[1] https://lwn.net/Articles/422330/

**Comment by alexcrichton** [comment]
This might perhaps nowadays be best added to https://crates.io/crates/socket2 which may be more suitable as it more closely matches C?

**Comment by ghost** [comment]
Sounds totally reasonable.

I wasn't aware of sockets2. Thanks @alexcrichton!
