### ISSUE TITLE
Move Repository To rust-lang

### ISSUE THREAD

**Issue by XAMPPRocky** [alexcrichton/net2-rs#91]
Hello, the current `rust-lang-nursery` organisation is considered deprecated, and the Rust Programming Language organisation is trying to consolidate managing Rust's GitHub organisations, as such we'd like you to consider moving your repository to the main `rust-lang` organisation instead. 

### How Do I Move To `rust-lang`?
You most likely won't be able to transfer your repository directly, if so you'll need to transfer your repository to @Mark-Simulacrum, who will then move your repository to the `rust-lang` organisation.

### Deprecating
If you no longer intend to maintain this repository, please let us know and we will take of deprecating the project.

**Comment by alexcrichton** [comment]
This repository doesn't have an official maintainer per se, it's sort of defactor been me and @sfackler from @rust-lang/libs. I don't think many of us are too thrilled to maintain this crate much more, and use of it is largely focused on [`socket2`](https://crates.io/crates/socket2) now at this point.

I think this is a good opportunity to take to deprecate the project personally. If someone would like to step up and maintain this, though, they're more than welcome to!

**Comment by sfackler** [comment]
👍 on deprecating

**Comment by bluejekyll** [comment]
As a consumer of this, then socket2, I agree. Deprecate.

**Comment by pfmooney** [comment]
Marked as deprecated and under sustaining maintenance only.
