### ISSUE TITLE
Documentation link on crates.io goes to a 404

### ISSUE THREAD

**Issue by alex** [alexcrichton/net2-rs#95]
The docs link on crates.io for `net2` points at https://doc.rust-lang.org/net2-rs/ which is a 404 now :-(

**Comment by zonyitoo** [comment]
@alexcrichton Hello Alex, could you fix it?

**Comment by alexcrichton** [comment]
Sorry but I don't personally have time to maintain this crate any more.

**Comment by zonyitoo** [comment]
So this crate will be replaced by `socket2` in the future?

**Comment by alexcrichton** [comment]
It sort of already has a bit, but yes I would recommend users use `socket2` instead

**Comment by pfmooney** [comment]
Fixed
